#Seasonality Test - G-Fisher

#ReadME: This R script evluates the seasonality of a set of time series.
#Based on the seasonality test the program will generate an output table of the RPKMS 
#that are significant seasonal and those that not (non-seasonal)

#The output generated by this code, then can be used to run ChronoClustR.R independently.

#!/usr/bin/env Rscript
args = commandArgs(trailingOnly=TRUE)

#Read arguments
countwec <- read.table(args[1],header=T, row.names=1, check.names=F, sep ="\t") #RPKM table of time-series
VIR_cl_env <- read.table(args[2],header=T, row.names=1, check.names=F, sep ="\t") #Metadata
output_path <- args[3] #output path
start_year <- as.integer(args[4]) #TSconversor parameters
start_month <- as.integer(args[5]) #TSconversor parameters
end_year <- as.integer(args[6]) #TSconversor parameters
end_month <- as.integer(args[7]) #TSconversor parameters
frequency_all <- as.integer(args[8]) #TSconversor parameters

# Check that output path ends with a slash, if not add it
if (!grepl("/$", output_path)) {
    output_path <- paste0(output_path, "/")
}

# Check if the output directory exists, if not, create it
if (!dir.exists(output_path)) {
    dir.create(output_path, recursive = TRUE)
}

rm(args)


#load libraries
library(tidyverse)
library(ggplot2)
library(cowplot) 
library(vegan)
library(reshape2)
library(ggpubr)
library(splines2)
library(ggridges)
library(pacman)
library(psych)
library(fpc)
library(factoextra)
library(gplots)
library(gridExtra)
library(corrplot)
library(dtwclust)
library(TSclust)
library(GeneCycle) #this library performs the fisher.g.test
library(zoo) #this library performs the interpolation
library(ggrepel)
library(KneeArrower)

###DEFINE FUNCTIONS###

#NOW IN Z-SCORE as it is in the overall table
#FUNCTION 1: convert our datasets into a time-series object
 ts_conversor<- function(df, s=c(start_year, start_month), e=c(end_year,end_month), f=frequency_all ){
 ts(df$value, start = s, end=e, frequency = f) 
 }

#FUNCTION 2 check for seasonality 
check_seasonality_fisher <- function(ls){
  ls %>% 
    map(~ts_conversor(.x)) %>% 
    map(~data.frame(per = periodogram(.)$freq[
      which.max(periodogram(.)$spec)],
      whole = periodogram(.),
      pval = fisher.g.test(.))) %>% 
  bind_rows( .id = "variable") 
}

#SEASONALITY TEST#
countwect<-t(countwec)

VIR_cl_env$sample<-rownames(VIR_cl_env)
VIR_cl_envdate<-VIR_cl_env[ , c("sample","Date_wavelet")]
VIR_cl_envdate$sample<-paste0("X",1:nrow(VIR_cl_envdate),".",VIR_cl_envdate$sample)

monthly_RPKM<-merge(VIR_cl_envdate,countwect,by=0, all = TRUE) ######I need to interpolate this
monthly_RPKM$Date_wavelet<-as.Date(monthly_RPKM$Date_wavelet,"%d/%m/%Y")
monthly_RPKM_sorted<-(monthly_RPKM[order(monthly_RPKM$Date_wavelet),]) #dim 32 26854

#Interpolation of the numerical columns. I;m skipping 1:3 becuase these are other alphanumerical strings (Row.names-sample-Date_wavelet)
monthly_RPKM_sort_trim_int<- data.frame(monthly_RPKM_sorted[1:3], na.approx(monthly_RPKM_sorted[4:length(monthly_RPKM_sorted)])) #na.approx fn -> interpolation
monthly_RPKM_sort_trim_int_cl<-monthly_RPKM_sort_trim_int[,c(3:length(monthly_RPKM_sorted))]
monthly_RPKM_sort_trim_int_cl_melt<-melt(monthly_RPKM_sort_trim_int_cl, id.vars=c("Date_wavelet"))

#Run the seasonal check
seasonal.check.RPKM <-monthly_RPKM_sort_trim_int_cl_melt %>% 
  split(.$variable,drop = T) %>% 
  check_seasonality_fisher()

#select unique rows
seasonal.check.RPKM_uniq<-seasonal.check.RPKM[!duplicated(seasonal.check.RPKM$variable),]

#select contigs names of unique less than 1X10-10
highly_seasonaldf<-seasonal.check.RPKM_uniq[ which(seasonal.check.RPKM_uniq$pval < 0.05), ][,1]
non_seasonaldf<-seasonal.check.RPKM_uniq[ which(seasonal.check.RPKM_uniq$pval >= 0.05), ][,1]

#Subset these list from monthly_RPKM_sort_trim_int_cl_melt into two different data frames 
Seasonal_significant_DF_melt <- monthly_RPKM_sort_trim_int_cl_melt[monthly_RPKM_sort_trim_int_cl_melt$variable %in% highly_seasonaldf, ]
not_significant_DF_melt <- monthly_RPKM_sort_trim_int_cl_melt[monthly_RPKM_sort_trim_int_cl_melt$variable %in% non_seasonaldf, ]

#reshape the data frames
Seasonal_significant_DF<-dcast(data = Seasonal_significant_DF_melt,formula = Date_wavelet~variable,value.var = "value") #dim Seasonal_significant_DF 32 22697
not_significant_DF<-dcast(data = not_significant_DF_melt,formula = Date_wavelet~variable,value.var = "value") 

#Remove the first column (date wavelet)
nums <- Seasonal_significant_DF[,2:length(Seasonal_significant_DF)] #Remove the wavelet column (1)
nums_nots<-not_significant_DF[,2:length(not_significant_DF)] #Remove the wavelet column (1)

#transpose both - These are the objects that can also be inputted if user has already checked the seasonality of its data
SignSeasonal_rpkms_subset<-t(nums) #contigs are rows #write.table(tnums, "/PATH/ctgs_interpolatedRPKMS.seasonal22k.tab", quote=FALSE, sep = "\t")
notsign_rpkms_subset<-t(nums_nots) #write.table(tnums_nots, "/PATH/ctgs_interpolatedRPKMS.notseasonal4k.tab", quote=FALSE, sep = "\t")

#Rename the column headers -> automatize this
colnames(SignSeasonal_rpkms_subset) <-VIR_cl_envdate$sample 
colnames(notsign_rpkms_subset)<- VIR_cl_envdate$sample 

#Reformat to the original column and rownames
SignSeasonal_rpkms_subset_ref<-SignSeasonal_rpkms_subset
notsign_rpkms_subset_ref<-notsign_rpkms_subset

colnames(SignSeasonal_rpkms_subset_ref) <- gsub("X[0-9]+\\.", "", colnames(SignSeasonal_rpkms_subset_ref))
colnames(notsign_rpkms_subset_ref) <- gsub("X[0-9]+\\.", "", colnames(notsign_rpkms_subset_ref))

rownames(SignSeasonal_rpkms_subset_ref) <- gsub("\\.\\.", "||", rownames(SignSeasonal_rpkms_subset_ref))
rownames(SignSeasonal_rpkms_subset_ref) <- gsub("\\.", "-", rownames(SignSeasonal_rpkms_subset_ref))
rownames(SignSeasonal_rpkms_subset_ref) <- gsub("^X", "", rownames(SignSeasonal_rpkms_subset_ref))

rownames(notsign_rpkms_subset_ref) <- gsub("\\.\\.", "||", rownames(notsign_rpkms_subset_ref))
rownames(notsign_rpkms_subset_ref) <- gsub("\\.", "-", rownames(notsign_rpkms_subset_ref))
rownames(notsign_rpkms_subset_ref) <- gsub("^X", "", rownames(notsign_rpkms_subset_ref))

output_file_seas <- paste0(output_path, "Seasonal_timeseries.txt")
output_file_nonseas <- paste0(output_path, "Non_seasonal_timeseries.txt")

write.table(SignSeasonal_rpkms_subset_ref, file=output_file_seas, , quote=FALSE, sep = "\t")
write.table(notsign_rpkms_subset_ref, file=output_file_nonseas, , quote=FALSE, sep = "\t")
